"""Initial migration

Revision ID: a2a02e9ae2fd
Revises: 
Create Date: 2025-05-25 19:27:40.000326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a02e9ae2fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('commissioned_date', sa.Integer(), nullable=True),
    sa.Column('stricken_date', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_id'), 'ships', ['id'], unique=False)
    op.create_index(op.f('ix_ships_name'), 'ships', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_name'), table_name='ships')
    op.drop_index(op.f('ix_ships_id'), table_name='ships')
    op.drop_table('ships')
    # ### end Alembic commands ###
